### ISSUE TITLE
Icon doesn't display properly

### ISSUE THREAD

**Issue by AhRoon** [Hypnootize/Sunset-Hud#3]
Hello,

I installed hud properly by installing the font, but icon is broken and still display as '?'.
I tried reinstalling the font, but still same issue.

Can you fix it?
![Sunset Hud (Bug Report #1)](https://user-images.githubusercontent.com/25527589/72655355-87f5b480-39d7-11ea-9644-d5a54aa70166.jpg)

**Comment by Hypnootize** [comment]
Hey, I reworked the icons font whenever you can could you try the new version released today and see if the problem is fixed, it would be really useful!

sidenote, i change the installation process a bit so checkout the installation file for any problem!

**Comment by AhRoon** [comment]
Okay, I will try your hud soon, and will let you know if hud works well! :)

**Comment by AhRoon** [comment]
Wow! Icons now display properly, thank you for the fix!

**Comment by Hypnootize** [comment]
Oh nice, I wasn't really sure that was gonna work but hey looks like it does :D
Thank you for confirming it!
